version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "4200:80"
  
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
