name: Update Docker Containers

on:
  push:
    branches:
      - main

jobs:
  update-containers:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Log out from Docker Hub
      run: docker logout
