name: Deploy on Self-Hosted Windows Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        uses: actions/checkout@v2

      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Rebuild and run containers
        run: docker-compose up -d --build

      - name: Docker logout
        run: docker logout
